version: "3.10"

services:
  db:
    image: postgres:15
    container_name: fastapi_postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - courses-net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - courses-net



  courses-service:
    build: ./app
    container_name: fastapi_courses
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/mydatabase
      - JWT_SECRET_KEY=supersecreta
    volumes:
      - .:/app
    networks:
      - courses-net

networks:
  courses-net:

volumes:
  postgres_data:
  pgdata: